### ISSUE TITLE
Support video services

### ISSUE THREAD

**Issue by msroberts** [GreenTreeLabs/EverlightBox#4]
I can see from the code that this plugin supports videos, but can it display videos from services like Vimeo in the lightbox?

**Comment by GreenTreeLabs** [comment]
Yes, Vimeo and YouTube are supported.

**Comment by msroberts** [comment]
How do I add a Vimeo video?  Do I need one of the gallery plugins?

**Comment by GreenTreeLabs** [comment]
Well a gallery it's not necessary. You can link an image to a Vimeo video but you'll need to add the class "everlightbox-trigger" to activate EverlightBox:

`<a href="https://vimeo.com/208342512" class="everlightbox-trigger">
       <img src="foo.jpg"  />
</a>`

**Comment by msroberts** [comment]
That worked.  Thanks!  Definitely using this plugin.

**Comment by GreenTreeLabs** [comment]
Cool!

P.S.: would you mind to rate it https://wordpress.org/support/plugin/everlightbox/reviews/ ;) ? Thanks!
